swagger: "2.0"
info:
  description: |
    This is a prototype ChRIS server.

    [Learn about ChRIS](https://github.com/FNNDSC/chrisreloaded/blob/master/README.md)or join the IRC channel `#babyMRI` on irc.freenode.net.

    ChRIS is a data management and processing workflow system.

    For this sample, you can use the api key `special-key` to test the authorization filters

  version: "1.0.0"
  title: ChRIS Backend
  termsOfService: http://helloreverb.com/terms/
  contact:
    name: dev@babymri.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: 98.110.227.249:8080
basePath: /v2
schemes:
  - http
paths:
  /feeds:
    post:
      tags:
        - feed
      summary: Add a new feed to the store
      description: ""
      operationId: addFeed
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: Feed object that needs to be added to the store
          required: false
          schema:
            $ref: "#/definitions/Feed"
      responses:
        "405":
          description: Invalid input
      security:
        - feedstore_auth:
          - write_feeds
          - read_feeds
    put:
      tags:
        - feed
      summary: Update an existing feed
      description: ""
      operationId: updateFeed
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: Feed object that needs to be added to the store
          required: false
          schema:
            $ref: "#/definitions/Feed"
      responses:
        "405":
          description: Validation exception
        "404":
          description: Feed not found
        "400":
          description: Invalid ID supplied
      security:
        - feedstore_auth:
          - write_feeds
          - read_feeds
  /feeds/findByStatus:
    get:
      tags:
        - feed
      summary: Finds Feeds by status
      description: Multiple status values can be provided with comma seperated strings
      operationId: findFeedsByStatus
      produces:
        - application/json
        - application/xml
      parameters:
        - in: query
          name: status
          description: Status values that need to be considered for filter
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Feed"
        "400":
          description: Invalid status value
      security:
        - feedstore_auth:
          - write_feeds
          - read_feeds
  /feeds/findByTags:
    get:
      tags:
        - feed
      summary: Finds Feeds by tags
      description: Muliple tags can be provided with comma seperated strings. Use tag1, tag2, tag3 for testing.
      operationId: findFeedsByTags
      produces:
        - application/json
        - application/xml
      parameters:
        - in: query
          name: tags
          description: Tags to filter by
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Feed"
        "400":
          description: Invalid tag value
      security:
        - feedstore_auth:
          - write_feeds
          - read_feeds
  /feeds/{feedId}:
    get:
      tags:
        - feed
      summary: Find feed by ID
      description: Returns a feed when ID < 10.  ID > 10 or nonintegers will simulate API error conditions
      operationId: getFeedById
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: feedId
          description: ID of feed that needs to be fetched
          required: true
          type: integer
          format: int64
      responses:
        "404":
          description: Feed not found
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Feed"
        "400":
          description: Invalid ID supplied
      security:
        - api_key: []
        - feedstore_auth:
          - write_feeds
          - read_feeds
    post:
      tags:
        - feed
      summary: Updates a feed in the store with form data
      description: ""
      operationId: updateFeedWithForm
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: feedId
          description: ID of feed that needs to be updated
          required: true
          type: string
        - in: formData
          name: name
          description: Updated name of the feed
          required: true
          type: string
        - in: formData
          name: status
          description: Updated status of the feed
          required: true
          type: string
      responses:
        "405":
          description: Invalid input
      security:
        - feedstore_auth:
          - write_feeds
          - read_feeds
    delete:
      tags:
        - feed
      summary: Deletes a feed
      description: ""
      operationId: deleteFeed
      produces:
        - application/json
        - application/xml
      parameters:
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        - in: path
          name: feedId
          description: Feed id to delete
          required: true
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid feed value
      security:
        - feedstore_auth:
          - write_feeds
          - read_feeds
  /stores/order:
    post:
      tags:
        - store
      summary: Place an order for a feed
      description: ""
      operationId: placeOrder
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: order placed for purchasing the feed
          required: false
          schema:
            $ref: "#/definitions/Order"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Order"
        "400":
          description: Invalid Order
  /stores/order/{orderId}:
    get:
      tags:
        - store
      summary: Find purchase order by ID
      description: For valid response try integer IDs with value <= 5 or > 10. Other values will generated exceptions
      operationId: getOrderById
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: orderId
          description: ID of feed that needs to be fetched
          required: true
          type: string
      responses:
        "404":
          description: Order not found
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Order"
        "400":
          description: Invalid ID supplied
    delete:
      tags:
        - store
      summary: Delete purchase order by ID
      description: For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
      operationId: deleteOrder
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: orderId
          description: ID of the order that needs to be deleted
          required: true
          type: string
      responses:
        "404":
          description: Order not found
        "400":
          description: Invalid ID supplied
  /users:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: Created user object
          required: false
          schema:
            $ref: "#/definitions/User"
      responses:
        default:
          description: successful operation
  /users/createWithArray:
    post:
      tags:
        - user
      summary: Creates list of users with given input array
      description: ""
      operationId: createUsersWithArrayInput
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: List of user object
          required: false
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
      responses:
        default:
          description: successful operation
  /users/createWithList:
    post:
      tags:
        - user
      summary: Creates list of users with given input array
      description: ""
      operationId: createUsersWithListInput
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: List of user object
          required: false
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
      responses:
        default:
          description: successful operation
  /users/login:
    get:
      tags:
        - user
      summary: Logs user into the system
      description: ""
      operationId: loginUser
      produces:
        - application/json
        - application/xml
      parameters:
        - in: query
          name: username
          description: The user name for login
          required: false
          type: string
        - in: query
          name: password
          description: The password for login in clear text
          required: false
          type: string
      responses:
        "200":
          description: successful operation
          schema:
            type: string
        "400":
          description: Invalid username/password supplied
  /users/logout:
    get:
      tags:
        - user
      summary: Logs out current logged in user session
      description: ""
      operationId: logoutUser
      produces:
        - application/json
        - application/xml
      responses:
        default:
          description: successful operation
  /users/{username}:
    get:
      tags:
        - user
      summary: Get user by user name
      description: ""
      operationId: getUserByName
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: username
          description: The name that needs to be fetched. Use user1 for testing.
          required: true
          type: string
      responses:
        "404":
          description: User not found
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/User"
        "400":
          description: Invalid username supplied
    put:
      tags:
        - user
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: updateUser
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: username
          description: name that need to be deleted
          required: true
          type: string
        - in: body
          name: body
          description: Updated user object
          required: false
          schema:
            $ref: "#/definitions/User"
      responses:
        "404":
          description: User not found
        "400":
          description: Invalid user supplied
    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: username
          description: The name that needs to be deleted
          required: true
          type: string
      responses:
        "404":
          description: User not found
        "400":
          description: Invalid username supplied
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
  feedstore_auth:
    type: oauth2
    authorizationUrl: http://feedstore.swagger.wordnik.com/api/oauth/dialog
    flow: implicit
    scopes:
      write_feeds: modify feeds in your account
      read_feeds: read your feeds
definitions:
  User:
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      userStatus:
        type: integer
        format: int32
        description: User Status
  Category:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Feed:
    required:
      - name
      - photoUrls
    properties:
      id:
        type: integer
        format: int64
      category:
        $ref: "#/definitions/Category"
      name:
        type: string
        example: doggie
      photoUrls:
        type: array
        items:
          type: string
      tags:
        type: array
        items:
          $ref: "#/definitions/Tag"
      status:
        type: string
        description: feed status in the store
  Tag:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Order:
    properties:
      id:
        type: integer
        format: int64
      feedId:
        type: integer
        format: int64
      quantity:
        type: integer
        format: int32
      shipDate:
        type: string
        format: date-time
      status:
        type: string
        description: Order Status
      complete:
        type: boolean

