#!/usr/bin/env python


"""

 _____ _    ______ _____ _____   _   _ _ _
/  __ \ |   | ___ \_   _/  ___| | | | | | |
| /  \/ |__ | |_/ / | | \ `--.  | | | | | |_ _ __ ___  _ __
| |   | '_ \|    /  | |  `--. \ | | | | | __| '__/ _ \| '_ \
| \__/\ | | | |\ \ _| |_/\__/ / | |_| | | |_| | | (_) | | | |
 \____/_| |_\_| \_|\___/\____/   \___/|_|\__|_|  \___/|_| |_|



font generated by:
http://patorjk.com/software/taag/#p=display&f=Doom&t=ChRIS%20Ultron

This module implements a simple comment-type class

"""

import  abc
import  json

import  os
import  sys

import  argparse

sys.path.append('components/rikeripsum/rikeripsum')
sys.path.append('components/names')
import  rikeripsum


class title(object):
    """
    This class implements a ChRIS style comment object.
    """

    __metaclass__   = abc.ABCMeta

    def __init__(self, **kwargs):

        self.contents   = ""

    def contents_rikeripsumBuild(self, **kwargs):
        """
        Populate the contents with default noise.
        :return:
        """

        wordCount = 10
        for key,val in kwargs.iteritems():
            if key == 'wordCount':  wordCount = int(val)

        self.contents = {'body': rikeripsum.generate_sentence(word_count=wordCount)}


    def __iter__(self):
        yield('title', self.contents)

def synopsis(ab_shortOnly = False):
    scriptName = os.path.basename(sys.argv[0])
    shortSynopsis =  '''
    SYNOPSIS

            %s                                     \\
                            --wordCount <wordCount>


    ''' % scriptName

    description =  '''
    DESCRIPTION

        `%s' is a simple "title" object handler for ChRIS.

    ARGS

       --wordCount <wordCount>
       The number of words in the title.


    ''' % (scriptName)
    if ab_shortOnly:
        return shortSynopsis
    else:
        return shortSynopsis + description

if __name__ == "__main__":

    parser      = argparse.ArgumentParser(description = synopsis(True))
    parser.add_argument(
        '-w', '--wordCount',
        help    =   "The number of words in generated text.",
        dest    =   'wordCount',
        action  =   'store',
        default =   10
    )

    args        = parser.parse_args()

    sample  = title()
    sample.contents_rikeripsumBuild(wordCount=args.wordCount)

    print(json.dumps(dict(sample)))

